export const finishModalCopy = {
  kicker: "Done here?",
  title: "END\nWORKOUT?",
  closeLabel: "Close",
  statTime: "Time",
  statSets: "Sets",
  statVolume: "Volume",
  finishAndSave: "FINISH & SAVE →",
  discard: "Discard workout",
  saving: "Saving...",
  savingAria: "Saving workout",
  drainFailed:
    "Couldn't sync with server — your data is saved locally and will sync next time you're online.",
  continueOffline: "CONTINUE →",
  unlocksKicker: "New this session",
  unlocksTitle: "UNLOCKED",
  newPrLabel: "NEW PR",
  unlockedLabel: "UNLOCKED",
  continueCta: "CONTINUE →",
  prTypeLabel: {
    "1rm": "1RM",
    volume: "VOL",
    reps: "REPS",
  },
} as const;
