// Generated by Supabase MCP from the live schema. Regenerate with
// `mcp__supabase__generate_typescript_types` and paste the output here.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5";
  };
  public: {
    Tables: {
      achievements: {
        Row: {
          criteria: Json;
          description: string;
          icon: string | null;
          id: string;
          slug: string;
          title: string;
        };
        Insert: {
          criteria: Json;
          description: string;
          icon?: string | null;
          id?: string;
          slug: string;
          title: string;
        };
        Update: {
          criteria?: Json;
          description?: string;
          icon?: string | null;
          id?: string;
          slug?: string;
          title?: string;
        };
        Relationships: [];
      };
      cardio_sessions: {
        Row: {
          created_at: string;
          distance_m: number | null;
          duration_sec: number;
          id: string;
          modality: Database["public"]["Enums"]["cardio_modality"];
          started_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          distance_m?: number | null;
          duration_sec: number;
          id?: string;
          modality: Database["public"]["Enums"]["cardio_modality"];
          started_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          distance_m?: number | null;
          duration_sec?: number;
          id?: string;
          modality?: Database["public"]["Enums"]["cardio_modality"];
          started_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
      exercise_muscles: {
        Row: {
          exercise_id: string;
          muscle_id: number;
          role: Database["public"]["Enums"]["muscle_role"];
        };
        Insert: {
          exercise_id: string;
          muscle_id: number;
          role: Database["public"]["Enums"]["muscle_role"];
        };
        Update: {
          exercise_id?: string;
          muscle_id?: number;
          role?: Database["public"]["Enums"]["muscle_role"];
        };
        Relationships: [
          {
            foreignKeyName: "exercise_muscles_exercise_id_fkey";
            columns: ["exercise_id"];
            isOneToOne: false;
            referencedRelation: "exercises";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "exercise_muscles_muscle_id_fkey";
            columns: ["muscle_id"];
            isOneToOne: false;
            referencedRelation: "muscles";
            referencedColumns: ["id"];
          },
        ];
      };
      exercises: {
        Row: {
          category: Database["public"]["Enums"]["exercise_category"];
          created_at: string;
          id: string;
          is_custom: boolean;
          name: string;
          primary_muscle: Database["public"]["Enums"]["muscle_group"];
          user_id: string | null;
        };
        Insert: {
          category?: Database["public"]["Enums"]["exercise_category"];
          created_at?: string;
          id?: string;
          is_custom?: boolean;
          name: string;
          primary_muscle: Database["public"]["Enums"]["muscle_group"];
          user_id?: string | null;
        };
        Update: {
          category?: Database["public"]["Enums"]["exercise_category"];
          created_at?: string;
          id?: string;
          is_custom?: boolean;
          name?: string;
          primary_muscle?: Database["public"]["Enums"]["muscle_group"];
          user_id?: string | null;
        };
        Relationships: [];
      };
      muscles: {
        Row: {
          id: number;
          muscle_group: Database["public"]["Enums"]["muscle_group"];
          name: string;
        };
        Insert: {
          id?: number;
          muscle_group: Database["public"]["Enums"]["muscle_group"];
          name: string;
        };
        Update: {
          id?: number;
          muscle_group?: Database["public"]["Enums"]["muscle_group"];
          name?: string;
        };
        Relationships: [];
      };
      personal_records: {
        Row: {
          achieved_at: string;
          exercise_id: string;
          id: string;
          pr_type: Database["public"]["Enums"]["pr_type"];
          set_id: string | null;
          user_id: string;
          value: number;
        };
        Insert: {
          achieved_at?: string;
          exercise_id: string;
          id?: string;
          pr_type: Database["public"]["Enums"]["pr_type"];
          set_id?: string | null;
          user_id: string;
          value: number;
        };
        Update: {
          achieved_at?: string;
          exercise_id?: string;
          id?: string;
          pr_type?: Database["public"]["Enums"]["pr_type"];
          set_id?: string | null;
          user_id?: string;
          value?: number;
        };
        Relationships: [
          {
            foreignKeyName: "personal_records_exercise_id_fkey";
            columns: ["exercise_id"];
            isOneToOne: false;
            referencedRelation: "exercises";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "personal_records_set_id_fkey";
            columns: ["set_id"];
            isOneToOne: false;
            referencedRelation: "sets";
            referencedColumns: ["id"];
          },
        ];
      };
      sets: {
        Row: {
          completed_at: string;
          id: string;
          reps: number;
          set_number: number;
          weight_kg: number;
          workout_exercise_id: string;
        };
        Insert: {
          completed_at?: string;
          id?: string;
          reps: number;
          set_number: number;
          weight_kg: number;
          workout_exercise_id: string;
        };
        Update: {
          completed_at?: string;
          id?: string;
          reps?: number;
          set_number?: number;
          weight_kg?: number;
          workout_exercise_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "sets_workout_exercise_id_fkey";
            columns: ["workout_exercise_id"];
            isOneToOne: false;
            referencedRelation: "workout_exercises";
            referencedColumns: ["id"];
          },
        ];
      };
      user_achievements: {
        Row: {
          achievement_id: string;
          unlocked_at: string;
          user_id: string;
        };
        Insert: {
          achievement_id: string;
          unlocked_at?: string;
          user_id: string;
        };
        Update: {
          achievement_id?: string;
          unlocked_at?: string;
          user_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "user_achievements_achievement_id_fkey";
            columns: ["achievement_id"];
            isOneToOne: false;
            referencedRelation: "achievements";
            referencedColumns: ["id"];
          },
        ];
      };
      workout_exercises: {
        Row: {
          exercise_id: string;
          id: string;
          position: number;
          workout_id: string;
        };
        Insert: {
          exercise_id: string;
          id?: string;
          position: number;
          workout_id: string;
        };
        Update: {
          exercise_id?: string;
          id?: string;
          position?: number;
          workout_id?: string;
        };
        Relationships: [
          {
            foreignKeyName: "workout_exercises_exercise_id_fkey";
            columns: ["exercise_id"];
            isOneToOne: false;
            referencedRelation: "exercises";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "workout_exercises_workout_id_fkey";
            columns: ["workout_id"];
            isOneToOne: false;
            referencedRelation: "workouts";
            referencedColumns: ["id"];
          },
        ];
      };
      workouts: {
        Row: {
          created_at: string;
          finished_at: string | null;
          id: string;
          notes: string | null;
          started_at: string;
          user_id: string;
        };
        Insert: {
          created_at?: string;
          finished_at?: string | null;
          id?: string;
          notes?: string | null;
          started_at?: string;
          user_id: string;
        };
        Update: {
          created_at?: string;
          finished_at?: string | null;
          id?: string;
          notes?: string | null;
          started_at?: string;
          user_id?: string;
        };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      cardio_modality: "walk" | "run" | "treadmill";
      exercise_category: "strength" | "cardio";
      muscle_group: "Chest" | "Back" | "Shoulders" | "Arms" | "Legs" | "Core";
      muscle_role: "primary" | "secondary";
      pr_type: "1rm" | "volume" | "reps";
    };
    CompositeTypes: Record<string, never>;
  };
};

export type MuscleGroup = Database["public"]["Enums"]["muscle_group"];
export type CardioModality = Database["public"]["Enums"]["cardio_modality"];
export type ExerciseCategory = Database["public"]["Enums"]["exercise_category"];
export type MuscleRole = Database["public"]["Enums"]["muscle_role"];

export type Exercise = Database["public"]["Tables"]["exercises"]["Row"];
export type Muscle = Database["public"]["Tables"]["muscles"]["Row"];

export const MUSCLE_GROUPS: readonly MuscleGroup[] = [
  "Chest",
  "Back",
  "Shoulders",
  "Arms",
  "Legs",
  "Core",
] as const;
