export const loginCopy = {
  heading: "Log in",
  subheading: "We'll email you a 6-digit code.",
  emailLabel: "Email",
  emailPlaceholder: "you@example.com",
  submit: "Send code",
  submitting: "Sending…",
  sent: "Check your email for the code.",
  codeLabel: "6-digit code",
  codePlaceholder: "123456",
  verify: "Log in",
  verifying: "Logging in…",
  changeEmail: "Use a different email",
  error: "Something went wrong. Try again.",
  invalidCode: "That code didn't work. Try again.",
} as const;
