export const activeWorkoutCopy = {
  back: "← Back",
  finish: "Finish",
  emptyHint: "No exercises yet. Tap Add Exercise.",
  currentSetLabel: (n: number): string => `SET ${n}`,
  setRowCheck: "✓",
  logSet: "LOG SET →",
  lastSessionPrefix: "Last session ·",
  prLabel: "Personal records",
  pr1rm: "1RM",
  prVolume: "VOL",
  prReps: "REPS",
  newPr: "NEW PR",
  sessionLabel: "Session",
  statVolume: "Volume",
  statSets: "Sets",
  statExercises: "Exercises",
  todayLabel: "Today",
  addExercise: "+ Add exercise",
} as const;
