export const activeWorkoutCopy = {
  back: "← Back",
  finish: "Finish",
  emptyHint: "No exercises yet. Tap Add Exercise.",
  currentSetLabel: (n: number): string => `SET ${n}`,
  setRowCheck: "✓",
  logSet: "LOG SET →",
  lastSessionPrefix: "Last session ·",
  sessionLabel: "Session",
  statVolume: "Volume",
  statSets: "Sets",
  statExercises: "Exercises",
  todayLabel: "Today",
  addExercise: "+ Add exercise",
} as const;
