export const cardioLink = "block";
export const cardioCard = "p-3 flex items-center gap-3";
export const cardioMascot = "w-10 h-10 flex-shrink-0";
export const cardioBody = "flex-1";
export const cardioTopRow = "flex items-center justify-between";
export const cardioTitle = "display text-sm";
export const cardioStats = "kicker";
export const cardioEmpty = "text-xs font-bold opacity-60";
export const cardioPips = "flex gap-1 mt-1.5";
